// vue/api-examples/src/components/CameraSelect/index.vue
<template>
  <div class="camera-dropdown" :style="style">
    Camera:
    <el-dropdown :style="{ marginLeft: '10px' }">
      <el-button type="primary">
        {{ label }}<el-icon class="el-icon--right"><arrow-down /></el-icon>
      </el-button>
      <template #dropdown>
        <el-dropdown-menu>
          <el-dropdown-item v-for="item in items" :key="item.id" @click="click(item.id)">
            <span :class="{ active: item.label == label }">{{ item.label }}</span></el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>
  </div>
</template>


<script setup>
import AgoraRTC from "agora-rtc-sdk-ng"
import {  onMounted, ref, unref, watch, isRef } from 'vue';

const items = ref([])
const label = ref('')

const props = defineProps({
  style: {
    type: Object,
    default: {}
  },
  videoTrack: {
    type: Object,
    default: null
  }
})


const videoTrack = ref(props.videoTrack)

onMounted(async () => {
  const devices = await AgoraRTC.getCameras()
  items.value = devices.map(item => ({ label: item.label, id: item.deviceId }))
  if (videoTrack.value) {
    label.value = videoTrack.value?.getTrackLabel()
  }
})

watch(() => props.videoTrack, (track) => {
  label.value = track?.getTrackLabel()
  videoTrack.value = track
})


AgoraRTC.onCameraChanged = async changedDevice => {
  const devices = await AgoraRTC.getCameras()
  items.value = devices.map(item => ({ label: item.label, id: item.deviceId }))
  if (changedDevice.state === "ACTIVE") {
    await videoTrack.value?.setDevice(changedDevice.device.deviceId);
    label.value = videoTrack.value?.getTrackLabel()
  } else if (changedDevice.device.label === label.value) {
    if (devices[0]) {
      await videoTrack.value?.setDevice(devices[0].deviceId);
      label.value = videoTrack.value?.getTrackLabel()
    }
  }
}

const click = async (id) => {
  if (videoTrack.value) {
    await videoTrack.value?.setDevice(id);
    label.value = videoTrack.value?.getTrackLabel()
  }
}


</script>



<style>
.camera-dropdown {
  display: flex;
  align-items: center;
  width: 100%;
  height: 40px;
  line-height: 40px;
  font-size: 14px;
}
</style>

// react/api-examples/src/components/CameraSelect/index.jsx
import AgoraRTC from "agora-rtc-sdk-ng";
import { Dropdown, Space, Typography } from "antd";
import { DownOutlined } from '@ant-design/icons';
import { useState, useRef, useEffect, useCallback } from "react";
const {
  Text
} = Typography;
const CameraSelect = ({
  videoTrack,
  style = {}
}) => {
  const [items, setItems] = useState([]);
  const [videoTrackLabel, setVideoTrackLabel] = useState("");
  useEffect(() => {
    if (videoTrack) {
      const label = videoTrack?.getTrackLabel();
      setVideoTrackLabel(label);
      AgoraRTC.getCameras().then(cams => {
        setItems(cams.map(item => ({
          label: item.label,
          key: item.deviceId
        })));
      });
    }
  }, [videoTrack]);
  useEffect(() => {
    AgoraRTC.onCameraChanged = async changedDevice => {
      const cameras = await AgoraRTC.getCameras();
      setItems(cameras.map(item => ({
        label: item.label,
        key: item.deviceId
      })));
      // When plugging in a device, switch to a device that is newly plugged in.
      if (changedDevice.state === "ACTIVE") {
        await videoTrack.setDevice(changedDevice.device.deviceId);
        setVideoTrackLabel(videoTrack?.getTrackLabel());
        // Switch to an existing device when the current device is unplugged.
      } else if (changedDevice.device.label === videoTrackLabel) {
        if (cameras[0]) {
          await videoTrack.setDevice(cameras[0].deviceId);
          setVideoTrackLabel(videoTrack?.getTrackLabel());
        }
      }
    };
  }, [videoTrackLabel]);
  const onClickItem = async ({
    key
  }) => {
    if (videoTrack) {
      await videoTrack.setDevice(key);
      setVideoTrackLabel(videoTrack?.getTrackLabel());
    }
  };
  return <div style={style}>
    <Space>
      <Text>Camera: </Text>
      <Dropdown menu={{
        items,
        selectable: true,
        onClick: onClickItem
      }} placement="bottom">
        <Space style={{
          cursor: "pointer"
        }}>
          <Text>{videoTrackLabel}</Text>
          <DownOutlined />
        </Space>
      </Dropdown>
    </Space>
  </div>;
};
export default CameraSelect;
