// vue/api-examples/src/components/MicrophoneSelect/index.vue
<template>
  <div class="microphone-dropdown" :style="style">
    Microphone:
    <el-dropdown :style="{ marginLeft: '10px' }">
      <el-button type="primary">
        {{ label }}<el-icon class="el-icon--right"><arrow-down /></el-icon>
      </el-button>
      <template #dropdown>
        <el-dropdown-menu>
          <el-dropdown-item v-for="item in items" :key="item.id" @click="click(item.id)">
            <span :class="{ active: item.label == label }">{{ item.label }}</span></el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>
  </div>
</template>


<script setup>
import AgoraRTC from "agora-rtc-sdk-ng"
import { onMounted, ref, unref, watch, isRef } from 'vue';

const items = ref([])
const label = ref('')

const props = defineProps({
  style: {
    type: Object,
    default: {}
  },
  audioTrack: {
    type: Object,
    default: null
  }
})

const audioTrack = ref(props.audioTrack)

onMounted(async () => {
  const devices = await AgoraRTC.getMicrophones()
  items.value = devices.map(item => ({ label: item.label, id: item.deviceId }))
  if (audioTrack.value) {
    label.value = audioTrack.value?.getTrackLabel()
  }
})

watch(() => props.audioTrack, (track) => {
  label.value = track?.getTrackLabel()
  audioTrack.value = track
})


AgoraRTC.onMicrophoneChanged = async changedDevice => {
  const devices = await AgoraRTC.getMicrophones()
  items.value = devices.map(item => ({ label: item.label, id: item.deviceId }))
  if (changedDevice.state === "ACTIVE") {
    await audioTrack.value?.setDevice(changedDevice.device.deviceId);
    label.value = audioTrack.value?.getTrackLabel()
  } else if (changedDevice.device.label === label.value) {
    if (devices[0]) {
      await audioTrack.value?.setDevice(devices[0].deviceId);
      label.value = audioTrack.value?.getTrackLabel()
    }
  }
}

const click = async (id) => {
  if (audioTrack.value) {
    await audioTrack.value?.setDevice(id);
    label.value = audioTrack.value?.getTrackLabel()
  }
}


</script>



<style>
.microphone-dropdown {
  display: flex;
  align-items: center;
  width: 100%;
  height: 40px;
  line-height: 40px;
  font-size: 14px;
}
</style>

// react/api-examples/src/components/MicrophoneSelect/index.jsx
import AgoraRTC from "agora-rtc-sdk-ng";
import { Dropdown, Button, Space, Typography } from "antd";
import { DownOutlined } from '@ant-design/icons';
import { useState, useRef, useEffect } from "react";
const {
  Text
} = Typography;
const MicrophoneSelect = ({
  audioTrack,
  style = {}
}) => {
  const [items, setItems] = useState([]);
  const [audioTrackLabel, setAudioTrackLabel] = useState('');
  useEffect(() => {
    if (audioTrack) {
      const label = audioTrack?.getTrackLabel();
      setAudioTrackLabel(label);
      AgoraRTC.getMicrophones().then(mics => {
        setItems(mics.map(item => ({
          label: item.label,
          key: item.deviceId
        })));
      });
    }
  }, [audioTrack]);
  useEffect(() => {
    AgoraRTC.onMicrophoneChanged = async changedDevice => {
      const mics = await AgoraRTC.getMicrophones();
      setItems(mics.map(item => ({
        label: item.label,
        key: item.deviceId
      })));
      // When plugging in a device, switch to a device that is newly plugged in.
      if (changedDevice.state === "ACTIVE") {
        await audioTrack.setDevice(changedDevice.device.deviceId);
        setAudioTrackLabel(audioTrack?.getTrackLabel());
        // Switch to an existing device when the current device is unplugged.
      } else if (changedDevice.device.label === audioTrackLabel) {
        if (mics[0]) {
          await audioTrack.setDevice(mics[0].deviceId);
          setAudioTrackLabel(audioTrack?.getTrackLabel());
        }
      }
    };
  }, [audioTrackLabel]);
  const onClickItem = async ({
    key
  }) => {
    if (audioTrack) {
      await audioTrack.setDevice(key);
      setAudioTrackLabel(audioTrack?.getTrackLabel());
    }
  };
  return <div style={style}>
    <Space>
      <Text>Microphone: </Text>
      <Dropdown menu={{
        items,
        selectable: true,
        onClick: onClickItem
      }} placement="bottom">
        <Space style={{
          cursor: "pointer"
        }}>
          <Text>{audioTrackLabel}</Text>
          <DownOutlined />
        </Space>
      </Dropdown>
    </Space>
  </div>;
};
export default MicrophoneSelect;
