// react/api-examples/src/components/MediaDeviceTest/index.jsx
import { useState, useRef, useImperativeHandle, forwardRef, useEffect, useCallback } from 'react'
import { Modal, Progress } from "antd"
import MicrophoneSelect from "../MicrophoneSelect"
import CameraSelect from "../CameraSelect"
import AgoraVideoPlayer from '../VideoPlayer'
import { useTranslation } from "react-i18next"


const MediaDeviceTest = forwardRef((props, ref) => {
  const {
    videoTrack,
    audioTrack
  } = props


  const { t } = useTranslation();
  const [open, setOpen] = useState(false)
  const [volume, setVolume] = useState(0)

  useEffect(() => {
    let intervalId = null
    if (audioTrack && open) {
      intervalId = setInterval(() => {
        const val = audioTrack.getVolumeLevel() * 100
        setVolume(val)
      }, 300)
    }

    return () => {
      clearInterval(intervalId)
    }
  }, [audioTrack, open])

  const show = () => {
    setOpen(true);
  };

  const hide = () => {
    setOpen(false);
  };


  useImperativeHandle(ref, () => ({
    show: show,
    hide: hide
  }))



  return <Modal
    title="Media Device Test"
    open={open}
    onOk={hide}
    onCancel={hide}
    okText={t('okText')}
    cancelText={t('cancelText')}
  >
    <MicrophoneSelect audioTrack={audioTrack}></MicrophoneSelect>
    <Progress percent={volume} status="active" showInfo={false} style={{ marginTop: "10px", marginBottom: "10px" }} />
    <CameraSelect videoTrack={videoTrack}></CameraSelect>
    <AgoraVideoPlayer style={{ marginTop: "10px" }} audioTrack={audioTrack} videoTrack={videoTrack} width={"240px"} height={"180px"}></AgoraVideoPlayer>
  </Modal>


})







export default MediaDeviceTest

// vue/api-examples/src/components/MediaDeviceTest/index.vue
<template>
  <el-dialog v-model="visible" title="Media Device Test" width="600px" :before-close="handleClose">
    <MicrophoneSelect :audioTrack="audioTrack"></MicrophoneSelect>
    <el-progress :percentage="volume" :show-text="false"
      :style="{ marginTop: '10px', marginBottom: '10px' }"></el-progress>
    <CameraSelect :videoTrack="videoTrack"></CameraSelect>
    <AgoraVideoPlayer :style="{ marginTop: '10px' }" :audioTrack="audioTrack" :videoTrack="videoTrack" width="240px"
      height="180px"></AgoraVideoPlayer>
  </el-dialog>
</template>



<script setup>
import { ref, watch, onMounted, onUnmounted } from "vue"

const visible = ref(false)
const volume = ref(0)
let intervalId = null

const props = defineProps({
  audioTrack: {
    type: Object,
    default: null
  },
  videoTrack: {
    type: Object,
    default: null
  }
})

defineExpose({
  show: () => {
    visible.value = true
  },
  hide: () => {
    visible.value = false
  }
})


watch(() => props.audioTrack, (track, oldTrack, onCleanup) => {
  if (track) {
    intervalId = setInterval(() => {
      const val = track.getVolumeLevel() * 100
      volume.value = val
    }, 300)
  }
  onCleanup(() => {
    if (intervalId) {
      clearInterval(intervalId)
    }
  })
})

const handleClose = () => {
  if (intervalId) {
    clearInterval(intervalId)
  }
  visible.value = false
}

onUnmounted(() => {
  if (intervalId) {
    clearInterval(intervalId)
  }
})

</script>
