// react/api-examples/src/components/NetworkTestDialog/index.jsx
import AgoraRTC from "agora-rtc-sdk-ng";
import { Button, Modal, Typography, message } from 'antd';
import { useRef, forwardRef, useImperativeHandle } from "react";
import { useState, useEffect } from 'react';
const {
  Text,
  Title,
  Paragraph
} = Typography;
const uplinkClient = AgoraRTC.createClient({
  mode: "rtc",
  codec: "vp8"
});
const downlinkClient = AgoraRTC.createClient({
  mode: "rtc",
  codec: "vp8"
});
let upClientUid = '';

// just use before join channel
const NetworkTestDialog = forwardRef((props, ref) => {
  const {
    title = 'Network Test',
    options = {}
  } = props;
  const [open, setOpen] = useState(false);
  const [uplinkNetworkQuality, setUplinkNetworkQuality] = useState(0);
  const [downlinkNetworkQuality, setDownlinkNetworkQuality] = useState(0);
  const [localAudioStats, setLocalAudioStats] = useState("");
  const [localVideoStats, setLocalVideoStats] = useState("");
  const [remoteAudioStats, setRemoteAudioStats] = useState("");
  const [remoteVideoStats, setRemoteVideoStats] = useState("");
  useEffect(() => {
    if (open) {
      doNetworkTest();
    }
    return () => {
      uplinkClient.leave();
      downlinkClient.leave();
    };
  }, [open]);
  useEffect(() => {
    uplinkClient.on("network-quality", handleUplinkNetworkQuality);
    downlinkClient.on("network-quality", handleDownlinkNetworkQuality);
    downlinkClient.on("user-published", handleUserPublished);
    return () => {
      uplinkClient.off("network-quality", handleUplinkNetworkQuality);
      downlinkClient.off("network-quality", handleDownlinkNetworkQuality);
      downlinkClient.off("user-published", handleUserPublished);
    };
  }, []);
  const handleUplinkNetworkQuality = quality => {
    setUplinkNetworkQuality(quality.uplinkNetworkQuality);
    setLocalAudioStats(JSON.stringify(uplinkClient.getLocalAudioStats()));
    setLocalVideoStats(JSON.stringify(uplinkClient.getLocalVideoStats()));
  };
  const handleDownlinkNetworkQuality = quality => {
    setDownlinkNetworkQuality(quality.downlinkNetworkQuality);
    setRemoteAudioStats(JSON.stringify(downlinkClient.getRemoteAudioStats()[upClientUid]));
    setRemoteVideoStats(JSON.stringify(downlinkClient.getRemoteVideoStats()[upClientUid]));
  };
  const handleUserPublished = async (user, mediaType) => {
    await downlinkClient.subscribe(user, mediaType);
  };
  const doNetworkTest = async () => {
    if (!options.appId) {
      const msg = "appId is required";
      message.error(msg);
      console.error(msg);
      hide();
      return;
    }
    if (!options.channel) {
      const msg = "channel is required";
      message.error(msg);
      console.error(msg);
      hide();
      return;
    }
    const tracks = await Promise.all([AgoraRTC.createMicrophoneAudioTrack(), AgoraRTC.createCameraVideoTrack()]);
    upClientUid = await uplinkClient.join(options.appId, options.channel, options.token || null, null);
    await downlinkClient.join(options.appId, options.channel, options.token || null, null);
    downlinkClient.on("user-published", async (user, mediaType) => {
      await downlinkClient.subscribe(user, mediaType);
    });
    await uplinkClient.publish(tracks);
  };
  const show = () => {
    setOpen(true);
  };
  const hide = () => {
    setOpen(false);
  };
  useImperativeHandle(ref, () => ({
    show: show,
    hide: hide
  }));
  return <Modal title={title} open={open} footer={null} onCancel={() => setOpen(false)}>
    <Title level={5}>Uplink</Title>
    <div>Network Quality: {uplinkNetworkQuality}</div>
    <Title level={5} style={{
      marginTop: "0.5em"
    }}>Local Audio Stats</Title>
    <div>{localAudioStats}</div>
    <Title level={5} style={{
      marginTop: "0.5em"
    }}>Local Video Stats</Title>
    <div>{localVideoStats}</div>
    <Title level={5} style={{
      marginTop: "0.5em"
    }}>Downlink</Title>
    <div>Network Quality: {downlinkNetworkQuality}</div>
    <Title level={5} style={{
      marginTop: "0.5em"
    }}>Remote Audio Stats</Title>
    <div>{remoteAudioStats}</div>
    <Title level={5} style={{
      marginTop: "0.5em"
    }}>Remote Video Stats</Title>
    <div>{remoteVideoStats}</div>
  </Modal>;
});
export default NetworkTestDialog;

// vue/api-examples/src/components/NetworkTestDialog/index.vue
<template>
  <el-dialog title="Network Test" v-model="open" width="650px" :before-close="hide">
    <div class="title">Uplink</div>
    <div class="sub-title" :style="{ marginTop: '0.5em' }">Network Quality: {{ uplinkNetworkQuality }}</div>
    <div :style="{ marginTop: '0.5em' }" class="text">Local Audio Stats</div>
    <div>{{ localAudioStats }}</div>
    <div :style="{ marginTop: '0.5em' }" class="text">Local Video Stats</div>
    <div>{{ localVideoStats }}</div>
    <div :style="{ marginTop: '0.5em' }" class="title">Downlink</div>
    <div class="sub-title" :style="{ marginTop: '0.5em' }">Network Quality: {{ downlinkNetworkQuality }}</div>
    <div :style="{ marginTop: '0.5em' }" class="text">Remote Audio Stats</div>
    <div>{{ remoteAudioStats }}</div>
    <div :style="{ marginTop: '0.5em' }" class="text">Remote Video Stats</div>
    <div>{{ remoteVideoStats }}</div>
  </el-dialog>
</template>


<script setup>
import { ref, watch, onMounted, onUnmounted } from "vue"
import { ElMessage } from 'element-plus'
import AgoraRTC from "agora-rtc-sdk-ng"

const open = ref(false)
const uplinkNetworkQuality = ref('')
const localAudioStats = ref('')
const localVideoStats = ref('')
const downlinkNetworkQuality = ref('')
const remoteAudioStats = ref('')
const remoteVideoStats = ref('')

let upClientUid = ''


const uplinkClient = AgoraRTC.createClient({
  mode: "rtc",
  codec: "vp8"
});

const downlinkClient = AgoraRTC.createClient({
  mode: "rtc",
  codec: "vp8"
});

const props = defineProps({
  options: {
    type: Object,
    default: () => { }
  }
})



const show = async () => {
  await doNetworkTest()
  open.value = true
}

const hide = () => {
  open.value = false
  unListenEvents()
  uplinkClient?.leave();
  downlinkClient?.leave();
}

defineExpose({
  show,
  hide
})

const listenEvents = () => {
  uplinkClient.on("network-quality", handleUplinkNetworkQuality)
  downlinkClient.on("network-quality", handleDownlinkNetworkQuality)
  downlinkClient.on("user-published", handleUserPublished);
}

const unListenEvents = () => {
  uplinkClient.off("network-quality", handleUplinkNetworkQuality)
  downlinkClient.off("network-quality", handleDownlinkNetworkQuality)
  downlinkClient.off("user-published", handleUserPublished);
}

onMounted(async () => {
  listenEvents()
})


onUnmounted(() => {
  unListenEvents()
})

const handleUplinkNetworkQuality = (quality) => {
  uplinkNetworkQuality.value = quality.uplinkNetworkQuality
  localAudioStats.value = JSON.stringify(uplinkClient.getLocalAudioStats())
  localVideoStats.value = JSON.stringify(uplinkClient.getLocalVideoStats())
}

const handleDownlinkNetworkQuality = (quality) => {
  downlinkNetworkQuality.value = quality.downlinkNetworkQuality
  remoteAudioStats.value = JSON.stringify(downlinkClient.getRemoteAudioStats()[upClientUid])
  remoteVideoStats.value = JSON.stringify(downlinkClient.getRemoteVideoStats()[upClientUid])
}

const handleUserPublished = async (user, mediaType) => {
  await downlinkClient.subscribe(user, mediaType);
}



const doNetworkTest = async () => {
  const { options } = props
  if (!options.appId) {
    const msg = "appId is required"
    ElMessage.error(msg)
    console.error(msg)
    hide()
    return
  }
  if (!options.channel) {
    const msg = "channel is required"
    ElMessage.error(msg)
    console.error(msg)
    hide()
    return
  }
  const tracks = await Promise.all([
    AgoraRTC.createMicrophoneAudioTrack(),
    AgoraRTC.createCameraVideoTrack()
  ]);

  upClientUid = await uplinkClient.join(options.appId, options.channel, options.token || null, null);
  await downlinkClient.join(options.appId, options.channel, options.token || null, null);
  downlinkClient.on("user-published", async (user, mediaType) => {
    await downlinkClient.subscribe(user, mediaType);
  })

  await uplinkClient.publish(tracks);
}

</script>


<style scoped>
.title {
  height: 26px;
  line-height: 26px;
  font-size: 20px;
  font-weight: bold;
}

.sub-title {
  height: 24px;
  line-height: 24px;
  font-size: 18px;
  font-weight: bold;
}

.text {
  height: 22px;
  line-height: 22px;
  font-size: 16px;
  font-weight: bold;
}
</style>
