// react/api-examples/src/components/CloudProxySelect/index.jsx
import { Dropdown, Button, Space, Typography } from "antd"
import { DownOutlined } from '@ant-design/icons';
import { useState, useRef, useEffect, useMemo } from "react";


const modes = [{
  label: "Close: Disable Cloud Proxy",
  key: "0",
}, {
  label: "UDP Mode: Enable Cloud Proxy via UDP protocol",
  key: "3",
}, {
  label: "TCP Mode: Enable Cloud Proxy via TCP/TLS port 443",
  key: "5",
}];


const CloudProxySelect = ({ defaultValue = '0', onChange }) => {
  const [mode, setMode] = useState(defaultValue)


  const onClickItem = async ({ key }) => {
    setMode(key)
    onChange && onChange(key)
  }


  return <Dropdown.Button type="primary"
    menu={{
      items: modes,
      selectable: true,
      selectedKeys: [mode],
      onClick: onClickItem
    }}
    placement="bottom"
    icon={<DownOutlined />} >
    Cloud Proxy
  </Dropdown.Button>
}

export default CloudProxySelect

// vue/api-examples/src/components/CloudProxySelect/index.vue
<template>
  <el-dropdown>
    <el-button type="primary">
      Cloud Proxy<el-icon class="el-icon--right"><arrow-down /></el-icon>
    </el-button>
    <template #dropdown>
      <el-dropdown-menu>
        <el-dropdown-item v-for="item in modes" :key="item.key" @click="click(item.key)">
          <span :class="{ active: item.key == key }">{{ item.label }}</span></el-dropdown-item>
      </el-dropdown-menu>
    </template>
</el-dropdown>
</template>


<script setup>
import { ref } from 'vue'

const modes = [{
  label: "Close: Disable Cloud Proxy",
  key: "0",
}, {
  label: "UDP Mode: Enable Cloud Proxy via UDP protocol",
  key: "3",
}, {
  label: "TCP Mode: Enable Cloud Proxy via TCP/TLS port 443",
  key: "5",
}];

const emit = defineEmits(['change'])
const key = ref('0')



const click = (val) => {
  key.value = val
  emit('change', val)
}

</script>
