// vue/api-examples/src/pages/advanced/dualStream/index.vue
<template>
  <div class="padding-20">
    <JoinForm ref="formRef"></JoinForm>
    <div class="btn-wrapper mt-10">
      <el-button type="primary" :disabled="joined" @click="join">Join</el-button>
      <el-button type="primary" :disabled="!joined" @click="leave">Leave</el-button>
    </div>
    <div v-if="joined" class="mt-10">
      <div class="text">Click Remote User Video Player Change Stream Type</div>
      <div class="text">Local User</div>
      <AgoraVideoPlayer :audioTrack="audioTrack" :videoTrack="videoTrack"></AgoraVideoPlayer>
    </div>
    <div v-if="Object.keys(remoteUsers).length">
      <div class="text">Remote Users</div>
      <AgoraVideoPlayer v-for="item in remoteUsers" :key="item.uid" ref="videoRefs" :videoTrack="item.videoTrack"
        :audioTrack="item.audioTrack" :text="item.uid" @click.native="onVideoClick(item.uid)">
      </AgoraVideoPlayer>
    </div>
  </div>
</template>

<script setup>
import AgoraRTC from "agora-rtc-sdk-ng"
import { onMounted, onUnmounted, ref } from "vue"
import { ElMessage } from 'element-plus'
import { useRoute } from "vue-router"
import { showJoinedMessage } from "../../../utils/utils"

const client = AgoraRTC.createClient({
  mode: "rtc",
  codec: "vp8"
});


const route = useRoute()
const { query } = route
const joined = ref(false)
const remoteUsers = ref({})
const audioTrack = ref(null)
const videoTrack = ref(null)
const formRef = ref()
const videoRefs = ref()


// uid -> streamType
const streamTypeMap = new Map()


onMounted(async () => {
  if (query.appId && query.channel) {
    formRef.value.setValue(query)
    join()
  }
})

onUnmounted(() => {
  if (joined.value) {
    leave()
  }
})


const initTracks = async () => {
  if (audioTrack.value && videoTrack.value) {
    return
  }
  const tracks = await Promise.all([
    AgoraRTC.createMicrophoneAudioTrack(),
    AgoraRTC.createCameraVideoTrack()
  ])
  audioTrack.value = tracks[0]
  videoTrack.value = tracks[1]
}

const handleUserPublished = async (user, mediaType) => {
  await client.subscribe(user, mediaType)
  delete remoteUsers.value[user.uid]
  remoteUsers.value[user.uid] = user
}

const handleUserUnpublished = (user, mediaType) => {
  if (mediaType == 'video') {
    delete remoteUsers.value[user.uid]
  }
}


const onVideoClick = async (uid) => {
  console.log('videoRefs', videoRefs)
  uid = Number(uid)
  const ref = videoRefs.current[uid]
  try {
    let finalStreamType = 1
    // streamType 0: high stream, 1: low stream
    if (streamTypeMap.has(uid)) {
      const streamType = streamTypeMap.get(uid)
      if (streamType === 0) {
        finalStreamType = 1
      } else {
        finalStreamType = 0
      }
    } else {
      finalStreamType = 1
    }
    streamTypeMap.set(uid, finalStreamType)
    let options = finalStreamType === 0 ? {
      width: "480px",
      height: "320px",
    } : {
      width: "160px",
      height: "120px",
    }
    ref.setOptions(options)
    await client.setRemoteVideoStreamType(uid, finalStreamType);
    message.info(`${uid} change stream type to ${finalStreamType === 0 ? "High" : "Low"}`)
  } catch (e) {
    console.error(e)
    message.error(e.message)
  }
}

const join = async () => {
  try {
    // Add event listeners to the client.
    client.on("user-published", handleUserPublished)
    client.on("user-unpublished", handleUserUnpublished);

    // Customize the video profile of the low-quality stream: 160 × 120, 15 fps, 120 Kbps.
    client.setLowStreamParameter({
      width: 160,
      height: 120,
      framerate: 15,
      bitrate: 120
    });
    // Enable dual-stream mode.
    await client.enableDualStream();

    const options = formRef.value.getValue()
    // Join a channel
    options.uid = await client.join(options.appId, options.channel, options.token || null, options.uid || null)
    await initTracks()
    const tracks = [audioTrack.value, videoTrack.value]
    await client.publish(tracks)
    showJoinedMessage(options)
    joined.value = true
  } catch (error) {
    console.error(error)
    ElMessage.error(error.message)
  }
}

const leave = async () => {
  if (audioTrack.value) {
    audioTrack.value.close()
    audioTrack.value = null
  }
  if (videoTrack.value) {
    videoTrack.value.close()
    videoTrack.value = null
  }
  remoteUsers.value = {}
  await client.leave()
  joined.value = false
  ElMessage.success('leave channel success!')
}

</script>

// react/api-examples/src/pages/advanced/dualStream/index.jsx
import AgoraRTC from "agora-rtc-sdk-ng"
import { useEffect, useRef, useState } from "react"
import { Button, Space, message, Typography, Dropdown } from "antd"
import { showJoinedMessage } from "@/utils/utils"
import { useUrlQuery } from "@/utils/hooks"
import JoinForm from "@/components/JoinForm"
import AgoraVideoPlayer from "@/components/VideoPlayer"


const { Title } = Typography;

const client = AgoraRTC.createClient({
  mode: "rtc",
  codec: "vp8"
});

let options = {}

// uid -> streamType
const streamTypeMap = new Map()

function DualStream() {
  const formRef = useRef()
  const query = useUrlQuery()
  const [joined, setJoined] = useState(false)
  const [videoTrack, setVideoTrack] = useState(null)
  const [audioTrack, setAudioTrack] = useState(null)
  const [remoteUsers, setRemoteUsers] = useState({})
  const videoRefs = useRef({})

  const initTracks = async () => {
    const tracks = await Promise.all([
      AgoraRTC.createMicrophoneAudioTrack(),
      AgoraRTC.createCameraVideoTrack()
    ])
    setAudioTrack(tracks[0])
    setVideoTrack(tracks[1])
    return tracks
  }

  useEffect(() => {
    return () => {
      joined && leave()
    }
  }, [joined])


  useEffect(() => {
    if (query.appId && query.channel) {
      formRef.current.setValue(query)
      setTimeout(() => {
        join()
      }, 1)
    }
  }, [query])


  /*
   * Add the local use to a remote channel.
   *
   * @param  {IAgoraRTCRemoteUser} user - The {@link  https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/iagorartcremoteuser.html| remote user} to add.
   * @param {trackMediaType - The {@link https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/itrack.html#trackmediatype | media type} to add.
   */
  const subscribe = async (user, mediaType) => {
    // subscribe to a remote user
    await client.subscribe(user, mediaType)
  }

  /*
   * Add a user who has subscribed to the live channel to the local interface.
   *
   * @param  {IAgoraRTCRemoteUser} user - The {@link  https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/iagorartcremoteuser.html| remote user} to add.
   * @param {trackMediaType - The {@link https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/itrack.html#trackmediatype | media type} to add.
   */
  const handleUserPublished = async (user, mediaType) => {
    const id = user.uid
    await subscribe(user, mediaType)
    setRemoteUsers((prev) => ({
      ...prev,
      [id]: user
    }))
  }

  /*
 * Remove the user specified from the channel in the local interface.
 *
 * @param  {string} user - The {@link  https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/iagorartcremoteuser.html| remote user} to remove.
 */
  const handleUserUnpublished = (user, mediaType) => {
    if (mediaType === 'video') {
      const id = user.uid
      setRemoteUsers(pre => {
        delete pre[id]
        return { ...pre }
      })
    }
  }




  const join = async () => {
    try {
      options = formRef.current.getValue()
      // Add event listeners to the client.
      client.on("user-published", handleUserPublished)
      client.on("user-unpublished", handleUserUnpublished);
      // Customize the video profile of the low-quality stream: 160 × 120, 15 fps, 120 Kbps.
      client.setLowStreamParameter({
        width: 160,
        height: 120,
        framerate: 15,
        bitrate: 120
      });
      // Enable dual-stream mode.
      await client.enableDualStream();
      // Join a channel
      options.uid = await client.join(options.appId, options.channel, options.token || null, options.uid || null)
      console.log("onVideoClick", options.uid, typeof options.uid)
      const tracks = await initTracks()
      await client.publish(tracks)
      showJoinedMessage(options)
      setJoined(true)
    } catch (error) {
      message.error(error.message)
      console.error(error)
    }
  }



  const leave = async () => {
    if (audioTrack) {
      audioTrack.close()
    }
    if (videoTrack) {
      videoTrack.close()
    }
    setRemoteUsers({})
    // leave the channel
    await client.leave()
    setJoined(false)
    console.log("client leaves channel success")
  }

  const onVideoClick = async (uid) => {
    uid = Number(uid)
    const ref = videoRefs.current[uid]
    try {
      let finalStreamType = 1
      // streamType 0: high stream, 1: low stream
      if (streamTypeMap.has(uid)) {
        const streamType = streamTypeMap.get(uid)
        if (streamType === 0) {
          finalStreamType = 1
        } else {
          finalStreamType = 0
        }
      } else {
        finalStreamType = 1
      }
      streamTypeMap.set(uid, finalStreamType)
      let options = finalStreamType === 0 ? {
        width: "480px",
        height: "320px",
      } : {
        width: "160px",
        height: "120px",
      }
      ref.setOptions(options)
      await client.setRemoteVideoStreamType(uid, finalStreamType);
      message.info(`${uid} change stream type to ${finalStreamType === 0 ? "High" : "Low"}`)
    } catch (e) {
      console.error(e)
      message.error(e.message)
    }
  }


  return <div className="padding-20">
    <JoinForm ref={formRef}></JoinForm>
    <Space style={{ marginTop: "10px" }}>
      <Button type="primary" onClick={join} disabled={joined}>Join with Dual Stream</Button>
      <Button onClick={leave} disabled={!joined}>Leave</Button>
    </Space>
    {joined ? <div className="mt-10">
      <Title level={5}>Click Remote User Video Player Change Stream Type</Title>
      <Title level={4}>Local User</Title>
      <AgoraVideoPlayer videoTrack={videoTrack} audioTrack={audioTrack}></AgoraVideoPlayer>
    </div> : null}
    {Object.keys(remoteUsers).length ?
      <div className="mt-10">
        <Title level={4}>Remote Users</Title>
        {Object.keys(remoteUsers).map(id => <AgoraVideoPlayer
          ref={item => videoRefs.current[id] = item}
          videoTrack={remoteUsers[id]?.videoTrack}
          audioTrack={remoteUsers[id]?.audioTrack}
          text={id}
          key={id}
          onClick={() => onVideoClick(id)}
        ></AgoraVideoPlayer>)}
      </div> : null}
  </div>

}

export default DualStream
