// vue/api-examples/src/pages/basic/shareTheScreen/index.vue
<template>
  <div class="padding-20">
    <JoinForm ref="formRef"></JoinForm>
    <div class="btn-wrapper mt-10">
      <el-button type="primary" :disabled="joined" @click="join">Join with screen video track</el-button>
      <el-button type="primary" :disabled="!joined" @click="leave">Leave</el-button>
    </div>
    <div v-if="joined" class="mt-10">
      <div class="text">Local User</div>
      <AgoraVideoPlayer :audioTrack="screenAudioTrack || audioTrack" :videoTrack="screenVideoTrack"></AgoraVideoPlayer>
    </div>
    <div v-if="Object.keys(remoteUsers).length">
      <div class="text">Remote Users</div>
      <AgoraVideoPlayer v-for="item in remoteUsers" :key="item.uid" :videoTrack="item.videoTrack"
        :audioTrack="item.audioTrack" :text="item.uid">
      </AgoraVideoPlayer>
    </div>
  </div>
</template>

<script setup>
import AgoraRTC from "agora-rtc-sdk-ng"
import { onMounted, onUnmounted, ref } from "vue"
import { ElMessage } from 'element-plus'
import { useRoute } from "vue-router"
import { showJoinedMessage } from "../../../utils/utils"


const client = AgoraRTC.createClient({
  mode: "rtc",
  codec: 'vp8'
});

const route = useRoute()
const { query } = route


const joined = ref(false)
const remoteUsers = ref({})
const audioTrack = ref()
const screenVideoTrack = ref()
const screenAudioTrack = ref()
const formRef = ref()


onMounted(async () => {
  if (query.appId && query.channel) {
    formRef.value.setValue(query)
    join()
  }
})

onUnmounted(() => {
  if (joined.value) {
    leave()
  }
})


//bind "track-ended" event, and when screensharing is stopped, there is an alert to notify the end user.
const handleTrackEnded = (e) => {
  if (screenVideoTrack.value) {
    screenVideoTrack.value.close()
    screenVideoTrack.value = null
  }
  if (screenAudioTrack.value) {
    screenAudioTrack.value.close()
    screenAudioTrack.value = null
  }
  if (audioTrack.value) {
    audioTrack.value.close()
    audioTrack.value = null
  }
}



const initTracks = async () => {
  const tempAudioTrack = await AgoraRTC.createMicrophoneAudioTrack()
  audioTrack.value = tempAudioTrack
  const tracks = await AgoraRTC.createScreenVideoTrack({
    encoderConfig: "720p"
  }, "auto")
  if (tracks instanceof Array) {
    screenVideoTrack.value = tracks[0]
    screenAudioTrack.value = tracks[1]
    tracks[0].on('track-ended', handleTrackEnded)
    return [tempAudioTrack, ...tracks]
  } else {
    screenVideoTrack.value = tracks
    tracks.on('track-ended', handleTrackEnded)
    return [tempAudioTrack, tracks]
  }
}

const handleUserPublished = async (user, mediaType) => {
  await client.subscribe(user, mediaType)
  delete remoteUsers.value[user.uid]
  remoteUsers.value[user.uid] = user
}

const handleUserUnpublished = (user, mediaType) => {
  if (mediaType == 'video') {
    delete remoteUsers.value[user.uid]
  }
}



const join = async () => {
  try {
    // Add event listeners to the client.
    client.on("user-published", handleUserPublished)
    client.on("user-unpublished", handleUserUnpublished);

    const options = formRef.value.getValue()
    // Join a channel
    options.uid = await client.join(options.appId, options.channel, options.token || null, options.uid || null)
    const tracks = await initTracks()
    await client.publish(tracks)
    showJoinedMessage(options)
    joined.value = true
  } catch (error) {
    console.error(error)
    ElMessage.error(error.message)
  }
}

const leave = async () => {
  screenAudioTrack.value?.close()
  screenVideoTrack.value?.close()
  audioTrack.value?.close()
  remoteUsers.value = {}
  await client.leave()
  joined.value = false
  ElMessage.success('leave channel success!')
}

</script>

// react/api-examples/src/pages/basic/shareTheScreen/index.jsx
import AgoraRTC from "agora-rtc-sdk-ng"
import { useEffect, useRef, useState } from "react"
import { Button, Space, message, Typography } from "antd"
import { showJoinedMessage } from "@/utils/utils"
import { useUrlQuery } from "@/utils/hooks"
import JoinForm from "@/components/JoinForm"
import AgoraVideoPlayer from "@/components/VideoPlayer"


const { Title } = Typography;

let client = AgoraRTC.createClient({
  mode: "rtc",
  codec: 'vp8'
});


function ShareTheScreen() {
  const formRef = useRef()
  const query = useUrlQuery()
  const [joined, setJoined] = useState(false)
  const [screenVideoTrack, setScreenVideoTrack] = useState(null)
  const [screenAudioTrack, setScreenAudioTrack] = useState(null)
  const [audioTrack, setAudioTrack] = useState(null)
  const [remoteUsers, setRemoteUsers] = useState({})

  const initTracks = async () => {
    const tempAudioTrack = await AgoraRTC.createMicrophoneAudioTrack()
    setAudioTrack(tempAudioTrack)
    const tracks = await AgoraRTC.createScreenVideoTrack({
      encoderConfig: "720p"
    }, "auto")
    if (tracks instanceof Array) {
      setScreenVideoTrack(tracks[0])
      setScreenAudioTrack(tracks[1])
      tracks[0].on('track-ended', handleTrackEnded)
      return [tempAudioTrack, ...tracks]
    } else {
      setScreenVideoTrack(tracks)
      tracks.on('track-ended', handleTrackEnded)
      return [tempAudioTrack, tracks]
    }
  }

  useEffect(() => {
    return () => {
      joined && leave()
    }
  }, [joined])


  useEffect(() => {
    if (query.appId && query.channel) {
      formRef.current.setValue(query)
      setTimeout(() => {
        join()
      }, 1)
    }
  }, [query])


  /*
   * Add the local use to a remote channel.
   *
   * @param  {IAgoraRTCRemoteUser} user - The {@link  https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/iagorartcremoteuser.html| remote user} to add.
   * @param {trackMediaType - The {@link https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/itrack.html#trackmediatype | media type} to add.
   */
  const subscribe = async (user, mediaType) => {
    await client.subscribe(user, mediaType)
  }

  /*
   * Add a user who has subscribed to the live channel to the local interface.
   *
   * @param  {IAgoraRTCRemoteUser} user - The {@link  https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/iagorartcremoteuser.html| remote user} to add.
   * @param {trackMediaType - The {@link https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/itrack.html#trackmediatype | media type} to add.
   */
  const handleUserPublished = async (user, mediaType) => {
    const id = user.uid
    await subscribe(user, mediaType)
    setRemoteUsers((prev) => ({
      ...prev,
      [id]: user
    }))
  }

  /*
 * Remove the user specified from the channel in the local interface.
 *
 * @param  {string} user - The {@link  https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/iagorartcremoteuser.html| remote user} to remove.
 */
  const handleUserUnpublished = (user, mediaType) => {
    if (mediaType === 'video') {
      const id = user.uid
      setRemoteUsers(pre => {
        delete pre[id]
        return { ...pre }
      })
    }
  }

  //bind "track-ended" event, and when screensharing is stopped, there is an alert to notify the end user.
  const handleTrackEnded = (e) => {
    if (screenVideoTrack) {
      screenVideoTrack.close()
      setScreenVideoTrack(null)
    }
    if (screenAudioTrack) {
      screenAudioTrack.close()
      setScreenAudioTrack(null)
    }
    if (audioTrack) {
      audioTrack.close()
      setAudioTrack(null)
    }
  }

  const join = async () => {
    try {
      const tracks = await initTracks()
      const options = formRef.current.getValue()
      // Add event listeners to the client.
      client.on("user-published", handleUserPublished)
      client.on("user-unpublished", handleUserUnpublished);
      // Join a channel
      options.uid = await client.join(options.appId, options.channel, options.token || null, options.uid || null)
      await client.publish(tracks)
      showJoinedMessage(options)
      setJoined(true)
    } catch (error) {
      message.error(error.message)
      console.error(error)
    }
  }

  const leave = async () => {
    if (audioTrack) {
      audioTrack.close()
    }
    if (screenVideoTrack) {
      screenVideoTrack.close()
    }
    if (screenAudioTrack) {
      screenAudioTrack.close()
    }
    setRemoteUsers({})
    // leave the channel
    await client.leave()
    setJoined(false)
    console.log("client leaves channel success")
  }



  return <div className="padding-20">
    <JoinForm ref={formRef}></JoinForm>
    <Space style={{ marginTop: "10px" }}>
      <Button type="primary" onClick={join} disabled={joined}>Join with screen video track</Button>
      <Button onClick={leave} disabled={!joined}>Leave</Button>
    </Space>
    {joined ? <div className="mt-10">
      <Title level={4}>Local User</Title>
      <AgoraVideoPlayer videoTrack={screenVideoTrack} audioTrack={screenAudioTrack || audioTrack}></AgoraVideoPlayer>
    </div> : null}
    {Object.keys(remoteUsers).length ?
      <div className="mt-10">
        <Title level={4}>Remote Users</Title>
        {Object.keys(remoteUsers).map(id => <AgoraVideoPlayer videoTrack={remoteUsers[id]?.videoTrack} audioTrack={remoteUsers[id]?.audioTrack} text={id} key={id}></AgoraVideoPlayer>)}
      </div> : null}
  </div>
}



export default ShareTheScreen
