// vue/api-examples/src/pages/basic/selfRendering/index.vue
<template>
  <div class="padding-20">
    <JoinForm ref="formRef"></JoinForm>
    <div class="btn-wrapper mt-10">
      <el-button :style="{ marginLeft: '10px' }" type="primary" :disabled="joined" @click="join">Join as host</el-button>
      <el-button :style="{ marginLeft: '10px' }" type="primary" :disabled="joined" @click="audienceJoin">Join as
        audience</el-button>
      <el-button type="primary" :disabled="!joined" @click="leave">Leave</el-button>
    </div>
    <div v-if="joined" class="mt-10">
      <div class="text">Local User</div>
      <AgoraVideoPlayer :audioTrack="audioTrack" :videoTrack="videoTrack"></AgoraVideoPlayer>
      <div :style="{ marginTop: '10px', display: 'inline-block', border: '2px dashed red' }">
        <video ref="mirrorPlayerRef" playsInline="" muted="" :style="{
          width: '480p',
          height: '320px',
          transform: 'rotateY(180deg)',
          objectFit: 'cover'
        }">
        </video>
      </div>
    </div>
    <div v-if="Object.keys(remoteUsers).length">
      <div class="text">Remote Users</div>
      <AgoraVideoPlayer v-for="item in remoteUsers" :key="item.uid" :videoTrack="item.videoTrack"
        :audioTrack="item.audioTrack" :text="item.uid">
      </AgoraVideoPlayer>
    </div>
  </div>
</template>

<script setup>
import AgoraRTC from "agora-rtc-sdk-ng"
import { onMounted, onUnmounted, ref } from "vue"
import { ElMessage } from 'element-plus'
import { useRoute } from "vue-router"
import { showJoinedMessage } from "../../../utils/utils"

let role = 'host'

const client = AgoraRTC.createClient({
  mode: "live",
  codec: "vp8"
});


const route = useRoute()
const { query } = route
const mirrorPlayerRef = ref()
const joined = ref(false)
const remoteUsers = ref({})
const audioTrack = ref(null)
const videoTrack = ref(null)
const formRef = ref()



onMounted(async () => {
  if (query.appId && query.channel) {
    formRef.value.setValue(query)
    join()
  }
})

onUnmounted(() => {
  if (joined.value) {
    leave()
  }
})



const initTracks = async () => {
  if (audioTrack.value && videoTrack.value) {
    return
  }
  const tracks = await Promise.all([
    AgoraRTC.createMicrophoneAudioTrack(),
    AgoraRTC.createCameraVideoTrack()
  ])
  audioTrack.value = tracks[0]
  videoTrack.value = tracks[1]
}

const handleUserPublished = async (user, mediaType) => {
  await client.subscribe(user, mediaType)
  delete remoteUsers.value[user.uid]
  remoteUsers.value[user.uid] = user
}

const handleUserUnpublished = (user, mediaType) => {
  if (mediaType == 'video') {
    delete remoteUsers.value[user.uid]
  }
}

const audienceJoin = () => {
  role = 'audience'
  join()
}



const join = async () => {
  try {
    client.setClientRole(role);
    // Add event listeners to the client.
    client.on("user-published", handleUserPublished)
    client.on("user-unpublished", handleUserUnpublished);

    const options = formRef.value.getValue()
    // Join a channel
    options.uid = await client.join(options.appId, options.channel, options.token || null, options.uid || null)
    await initTracks()
    const tracks = [audioTrack.value, videoTrack.value]
    if (role == 'host') {
      await client.publish(tracks)
    }
    showJoinedMessage(options)
    joined.value = true
    if (role == 'host') {
      selfRender()
    }
  } catch (error) {
    console.error(error)
    ElMessage.error(error.message)
  }
}

const leave = async () => {
  if (audioTrack.value) {
    audioTrack.value.close()
    audioTrack.value = null
  }
  if (videoTrack.value) {
    videoTrack.value.close()
    videoTrack.value = null
  }
  remoteUsers.value = {}
  await client.leave()
  joined.value = false
  ElMessage.success('leave channel success!')
}


const selfRender = () => {
  setTimeout(() => { 
    //get browser-native object MediaStreamTrack from WebRTC SDK
    const msTrack = videoTrack.value.getMediaStreamTrack()
    // generate browser-native object MediaStream with above video track
    const ms = new MediaStream([msTrack]);
    mirrorPlayerRef.value.srcObject = ms;
    mirrorPlayerRef.value.play();
  }, 0)
}

</script>

// react/api-examples/src/pages/basic/selfRendering/index.jsx
import AgoraRTC from "agora-rtc-sdk-ng"
import { useEffect, useRef, useState } from "react"
import { Button, Space, message, Typography, Dropdown } from "antd"
import { DownOutlined } from '@ant-design/icons';
import { showJoinedMessage } from "@/utils/utils"
import { useUrlQuery } from "@/utils/hooks"
import JoinForm from "@/components/JoinForm"
import AgoraVideoPlayer from "@/components/VideoPlayer"


const { Title, Text } = Typography;

const client = AgoraRTC.createClient({
  mode: "live",
  codec: "vp8"
});

const DEFAULT_LATENCY = '1'
const latencyItems = [
  {
    label: 'Interactive Live Streaming Standard',
    key: "1",
  },
  {
    label: 'Interactive Live Streaming Premium',
    key: "2",
  },
]


let audienceLatency = DEFAULT_LATENCY
let role = 'host'

function SelfRendering() {
  const formRef = useRef()
  const query = useUrlQuery()
  const [joined, setJoined] = useState(false)
  const [msTrack, setMsTrack] = useState(null)
  const [videoTrack, setVideoTrack] = useState(null)
  const [audioTrack, setAudioTrack] = useState(null)
  const [remoteUsers, setRemoteUsers] = useState({})
  const mirrorPlayerRef = useRef()

  const initTracks = async () => {
    const tracks = await Promise.all([
      AgoraRTC.createMicrophoneAudioTrack(),
      AgoraRTC.createCameraVideoTrack()
    ])
    setAudioTrack(tracks[0])
    setVideoTrack(tracks[1])
    return tracks
  }

  useEffect(() => {
    return () => {
      joined && client.leave()
    }
  }, [joined])


  useEffect(() => {
    if (joined && role == 'host') {
      //get browser-native object MediaStreamTrack from WebRTC SDK
      const msTrack = videoTrack.getMediaStreamTrack()
      // generate browser-native object MediaStream with above video track
      const ms = new MediaStream([msTrack]);
      mirrorPlayerRef.current.srcObject = ms;
      mirrorPlayerRef.current.play();
    }
  }, [joined])


  useEffect(() => {
    if (query.appId && query.channel) {
      formRef.current.setValue(query)
      setTimeout(() => {
        join()
      }, 1)
    }
  }, [query])


  /*
   * Add the local use to a remote channel.
   *
   * @param  {IAgoraRTCRemoteUser} user - The {@link  https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/iagorartcremoteuser.html| remote user} to add.
   * @param {trackMediaType - The {@link https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/itrack.html#trackmediatype | media type} to add.
   */
  const subscribe = async (user, mediaType) => {
    await client.subscribe(user, mediaType)
  }

  /*
   * Add a user who has subscribed to the live channel to the local interface.
   *
   * @param  {IAgoraRTCRemoteUser} user - The {@link  https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/iagorartcremoteuser.html| remote user} to add.
   * @param {trackMediaType - The {@link https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/itrack.html#trackmediatype | media type} to add.
   */
  const handleUserPublished = async (user, mediaType) => {
    const id = user.uid
    await subscribe(user, mediaType)
    setRemoteUsers((prev) => ({
      ...prev,
      [id]: user
    }))
  }

  /*
 * Remove the user specified from the channel in the local interface.
 *
 * @param  {string} user - The {@link  https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/iagorartcremoteuser.html| remote user} to remove.
 */
  const handleUserUnpublished = (user, mediaType) => {
    if (mediaType === 'video') {
      const id = user.uid
      setRemoteUsers(pre => {
        delete pre[id]
        return { ...pre }
      })
    }
  }

  const join = async () => {
    try {
      const options = formRef.current.getValue()
      // Add event listeners to the client.
      client.on("user-published", handleUserPublished)
      client.on("user-unpublished", handleUserUnpublished);
      if (role === 'audience') {
        client.setClientRole(role, {
          level: Number(audienceLatency)
        });
      } else {
        client.setClientRole(role);
      }
      // Join a channel
      options.uid = await client.join(options.appId, options.channel, options.token || null, options.uid || null)
      const tracks = await initTracks()
      if (role == 'host') {
        await client.publish(tracks)
      }
      showJoinedMessage(options)
      setJoined(true)
    } catch (error) {
      message.error(error.message)
      console.error(error)
    }
  }


  const hostJoin = () => {
    role = "host"
    join()
  }

  const audienceJoin = ({ key = DEFAULT_LATENCY }) => {
    role = 'audience'
    audienceLatency = key
    join()
  }

  const leave = async () => {
    if (audioTrack) {
      audioTrack.close()
    }
    if (videoTrack) {
      videoTrack.close()
    }
    setRemoteUsers({})
    // leave the channel
    await client.leave()
    setJoined(false)
    console.log("client leaves channel success")
  }


  return <div className="padding-20">
    <JoinForm ref={formRef}></JoinForm>
    <Space style={{ marginTop: "10px" }}>
      <Button type="primary" onClick={hostJoin} disabled={joined}>Join as host</Button>
      <Dropdown.Button
        type="primary"
        disabled={joined}
        icon={<DownOutlined />}
        onClick={audienceJoin}
        menu={{ items: latencyItems, selectable: true, onClick: audienceJoin }} placement="bottom">
        Join as audience
      </Dropdown.Button>
      <Button onClick={leave} disabled={!joined}>Leave</Button>
    </Space>
    {joined ? <div className="mt-10">
      <Title level={4}>Local User</Title>
      <AgoraVideoPlayer videoTrack={videoTrack} audioTrack={audioTrack}></AgoraVideoPlayer>
      <div style={{ marginTop: "10px", display: "inline-block", border: "2px dashed red" }}>
        <video ref={mirrorPlayerRef} playsInline="" muted=""
          style={{
            width: "480px", height: "320px", transform: "rotateY(180deg)", objectFit: "cover"
          }}>
        </video>
      </div>
    </div> : null}
    {
      Object.keys(remoteUsers).length ?
        <div className="mt-10">
          <Title level={4}>Remote Users</Title>
          {Object.keys(remoteUsers).map(id => <AgoraVideoPlayer videoTrack={remoteUsers[id]?.videoTrack} audioTrack={remoteUsers[id]?.audioTrack} text={id} key={id}></AgoraVideoPlayer>)}
        </div> : null
    }
  </div >
}


export default SelfRendering
